version: '3.2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: denden047/youyakuman:latest
    volumes:
      - type: bind
        source: ../src
        target: /workdir
      - type: bind
        source: ../checkpoint
        target: /checkpoint
      - type: bind
        source: ../model
        target: /model
      - type: bind
        source: ../data
        target: /data
    working_dir: /workdir
    command: python youyakuman.py --txt_file /data/testjp.txt --lang jp -n 3 --super_long
